### ISSUE TITLE
[Request for help] Is it possible to use multiple VMSS together with single load balancer?

### ISSUE THREAD

**Issue by ig-sinicyn** [Azure/vm-scale-sets#11]
We have multiple background worker vmss that do not need a public IP to work.

I want to be able to connect to arbitrary vm (e.g. to troubleshoot via rdp, or to collect some snapshots using remote profiler etc).

When there's only one VMSS per load balancer all works like a charm. I've setup nat pools for each port used on VMs and all works fine.
Now, if I'm trying to add one more vmss to the same load balancer (using its own nat / backend pools) the deployment fails with 
```
Virtual Machine /subscriptions/.../resourceGroups/.../providers/Microsoft.Compute/virtualMachines/\|providers\|Micr osoft.Compute\|virtualMachineScaleSets\|...\|virtualMachines\|0 is using different Availability Set than other Virtual Machines connected to the Load Balancer(s) ..."
```
message.

As far as I know there's no way to set up availability set for vmss. Are there any options but keeping own load balancer/public ip for each VMSS?

**UPD** I've found similar scheme for [VM+Availability Set setup](https://docs.microsoft.com/en-us/azure/load-balancer/load-balancer-internal-overview#intranet-line-of-business-applications) (see ILB endpoint section).

Something like this for VMSS?

**Comment by gbowerman** [comment]
@ig-sinicyn thanks for raising this. Your current options are:
- Use public IP per VM (ruled out by your first statement above).
- Create a 'jumpbox' standalone VM in the VNet with a public IP. Connect to VMs in the scale set from the jumpbox VM.
- Use the Azure Application Gateway. It supports up to 20 backend pools, and each pool can be referenced by a separate scale set. Just going into production now is support for multiple scale sets in the same backend pool.
- There is work in progress for future versions of ALB (Azure Load Balancer) will also support multiple scale sets.

**Comment by ig-sinicyn** [comment]
@gbowerman ok, thanks! We've resolved it with IP per vmss.
