### ISSUE TITLE
issue hack2017/DSC/Configuration.zip -> \MSFT_xRDSessionHostSelfAdd.psm1 add-rdserver new collection

### ISSUE THREAD

**Issue by jagilber** [Azure/vm-scale-sets#18]
hack2017/DSC/Configuration.zip ->\xRemoteDesktopSessionHost\DSCResources\MSFT_xRDSessionHostSelfAdd\MSFT_xRDSessionHostSelfAdd.psm1
part of issue #12 
moving add-rdserver to apply to both existing collections and new collections

**change from:**

 if ($collectionExists){
        write-verbose "Simply adding local server to RD Session collection '$CollectionName'"
        **Add-RDServer -Server $localhost -Role RDS-RD-SERVER -ConnectionBroker $ConnectionBroker**
        Add-RDSessionHost @PSBoundParameters -SessionHost $localhost
    }
    else {
        write-verbose "calling New-RdSessionCollection cmdlet..."
        New-RDSessionCollection @PSBoundParameters -SessionHost $localhost
    }

**change to:**

**Add-RDServer -Server $localhost -Role RDS-RD-SERVER -ConnectionBroker $ConnectionBroker**

 if ($collectionExists){
        write-verbose "Simply adding local server to RD Session collection '$CollectionName'"
        Add-RDSessionHost @PSBoundParameters -SessionHost $localhost
    }
    else {
        write-verbose "calling New-RdSessionCollection cmdlet..."
        New-RDSessionCollection @PSBoundParameters -SessionHost $localhost
    }

**Comment by ChristianMontoya** [comment]
Resolved by: Pull Request #19
