### ISSUE TITLE
Add Azure Load Balancer (layer-4) support for large scale sets (> 100 VM)

### ISSUE THREAD

**Issue by gregjhogan** [Azure/vm-scale-sets#3]
I was so excited when I saw support for scale sets up to 1000 VMs, but then disappointed when I discovered I can't put them all behind a single azure internal load balancer.  I currently run multiple scale sets with round-robin DNS, and I would like to switch to a single scale set with a single azure internal load balancer.

**Comment by gbowerman** [comment]
Thanks for logging this issue @gregjhogan - large scale set support for layer-4 load balancing is something we're working on, and we'll be updating this issue when there is more information to share.

**Comment by gbowerman** [comment]
@gregjhogan We've started a private preview for layer-4 load balancing support. Let me know if you're still interested. Thanks.

**Comment by gregjhogan** [comment]
This is available now and works great.  Thanks!
