### ISSUE TITLE
Unable to reset scaleset VM password during a cluster upgrade 

### ISSUE THREAD

**Issue by rajaprad** [Azure/vm-scale-sets#38]
On every cluster upgrade my organisational policy and need is to change the VMSS Machine passwords.
This was working fine for sometime in the past and lately failing with the bellow error,
"error": {
"code": "**PropertyChangeNotAllowed**",
"target": "adminPassword",
"message": "**Changing property 'adminPassword' is not allowed."**
}
}'

**Comment by gbowerman** [comment]
Hi, this property has never been modifiable for scale sets, so the recommendation was to use the VMAccess VM extension. 
However I am pleased to report that a solution to make this property modifiable in the VMSS model has recently been coded and we are starting to roll it out (will likely be in the December PowerShell/CLI builds).
I'll update this issue when it's available in one or more regions for testing.
Notes:
When admin credentials are modified in the VMSS properties:
New properties will apply to any new VMs created.
New properties will only apply to existing VMs if they are reimaged/upgraded - you'll need to script or manually update credentials on existing VMs if you don't want to reimage them.

**Comment by gbowerman** [comment]
Please give this a try with API version 2012-12-01 - it should work.

**Comment by rajaprad** [comment]
Doesn't seem to work with **2012-12-01**

  "error": {
    "code": "NoRegisteredProviderFound",
    "message": "No registered resource provider found for location 'eastus' and API version '2012-12-01' for type 'virtualMachines
'. The supported api-versions are '2015-05-01-preview, 2015-06-15, 2016-03-30, 2016-04-30-preview, 2016-08-30, 2017-03-30, 2017-12
-01'. The supported locations are 'eastus, eastus2, westus, centralus, northcentralus, southcentralus, northeurope, westeurope, ea
stasia, southeastasia, japaneast, japanwest, australiaeast, australiasoutheast, brazilsouth, southindia, centralindia, westindia,
canadacentral, canadaeast, westus2, westcentralus, uksouth, ukwest, koreacentral, koreasouth'."
  }
}'

**Comment by gbowerman** [comment]
@rajaprad sorry 2017-12-01.

**Comment by rajaprad** [comment]
Thanks @gbowerman, was able to work with 2016-03-30. But how does a consumer like me know that the api-version needs to be updated to a specific one to make things working ?

**Comment by gbowerman** [comment]
In this case, the functionality changed very recently and had not yet been documented, so there is no easy way to know this until the documentation is updated. The VM scale sets FAQ has now been updated and should go live this week.

**Comment by gbowerman** [comment]
Closing as fixed. see VMSS FAQ [https://docs.microsoft.com/en-us/azure/virtual-machine-scale-sets/virtual-machine-scale-sets-faq#compliance-and-security](https://docs.microsoft.com/en-us/azure/virtual-machine-scale-sets/virtual-machine-scale-sets-faq#compliance-and-security)
