### ISSUE TITLE
Wrong link (Deploy in Azure) for Low Priority VMSS

### ISSUE THREAD

**Issue by Gaploid** [Azure/vm-scale-sets#48]
There is a mistake on this page https://github.com/Azure/vm-scale-sets/tree/master/preview/lowpri on button deploy on Azure. It will deploy vmss with standard VMs and not Low priority,

**Comment by mmccrory** [comment]
This should be fixed. Please let me know if it is still not working for you. Thanks!

**Comment by gatneil** [comment]
Closing since it was fixed :)
