### ISSUE TITLE
Unable to see the data disk in the vm-scale-sets as well as in the azure portal

### ISSUE THREAD

**Issue by Saravanan-QWC** [Azure/vm-scale-sets#51]
I have tried adding data disks to the existing vm-scale-set. Used the following powershell command. 
```
# Get scale set object
$vmss = Get-AzureRmVmss `
          -ResourceGroupName "trans4m-rg" `
          -VMScaleSetName "prodwebvm"

# Attach a 128 GB data disk to LUN 1
Add-AzureRmVmssDataDisk `
  -VirtualMachineScaleSet $vmss `
  -CreateOption Empty `
  -Lun 1 `
  -DiskSizeGB 128

# Update the scale set to apply the change
Update-AzureRmVmss `
  -ResourceGroupName "trans4m-rg" `
  -Name "prodwebvm" `
  -VirtualMachineScaleSet $vmss

```
However the attached disk does not appear in disk management tool of the VM. Also, the disk does not appear in azure portal.

When I run the following powershell command, I am able to see the disks
`Get-AzureRmVmss -ResourceGroupName "trans4m-rg" -Name "prodwebvm"`

Any help appreciated

**Comment by gatneil** [comment]
What is your upgrade policy?

**Comment by Saravanan-QWC** [comment]
This is "Manual". After reading this [article](https://docs.microsoft.com/en-us/azure/virtual-machine-scale-sets/virtual-machine-scale-sets-upgrade-scale-set), I understand that I need "scale set instance view". How do I set the upgrade policy to this? so that I can get the data disk with its data.

**Comment by gatneil** [comment]
Actually, you need the part of that article that describes bringing VMs up to date with the latest model:

https://docs.microsoft.com/en-us/azure/virtual-machine-scale-sets/virtual-machine-scale-sets-upgrade-scale-set#how-to-bring-vms-up-to-date-with-the-latest-scale-set-model

Once you do the Update-AzureRmVmss command above, this updates the scale set model, but you need to do the manual upgraded step described in the doc to make it take effect on existing VMs. This is only needed in Manual upgrade mode, though :).

Hope this helps!

**Comment by Saravanan-QWC** [comment]
Deleted all existing instances expect my first instance. 
I updated the VM-scale-set with powershell command
`Update-AzureRmVmssInstance -ResourceGroupName "trans4m-rg" -VMScaleSetName "prodwebvm" -InstanceId 0`
Manually created an another new instance.
Even here, I am unable to see the IIS and data disk that are actually part of my instance "0"

**Comment by Saravanan-QWC** [comment]
I understood from azure resource explorer that my virtual machine scale set is set to manual by default
`"upgradePolicy": {
          "mode": "Manual",
          "automaticOSUpgrade": false
        },`
once i changed this into automatic, all worked perfect. 
`"upgradePolicy": {
          "mode": "Automatic",
          "automaticOSUpgrade": false
        },`

Thanks gatneil
