### ISSUE TITLE
Can I run a background window service with vm scale set?

### ISSUE THREAD

**Issue by mgolois** [Azure/vm-scale-sets#59]
Hello,
I've been looking at Azure Cloud Service (worker/web role), but apparently that option is classic and not recommended though still available.
My next option is the VM scale set. All I need is a VM that can run a windows console app as background service which will receive triggers/notifications from blob storage or service bus that a new file is ready to be processed.
I looked at Azure Functions, but most of the libraries I'm using are c++ native, it did not work.

Let me know,

Thanks!

**Comment by gbowerman** [comment]
Hi, you could create a custom VM image that runs the code you need and use that as the source image for your scale set, or use a platform image and add a VM extensions which installs the app when a new VM is created. The options are enumerated here: [https://docs.microsoft.com/en-us/azure/virtual-machine-scale-sets/virtual-machine-scale-sets-deploy-app](https://docs.microsoft.com/en-us/azure/virtual-machine-scale-sets/virtual-machine-scale-sets-deploy-app)

**Comment by mgolois** [comment]
ok. Thank you for the idea!
