### ISSUE TITLE
VMSS + latestModelApplied

### ISSUE THREAD

**Issue by stephenmontgomery** [Azure/vm-scale-sets#62]
Hi,
I was looking at https://docs.microsoft.com/en-us/azure/virtual-machine-scale-sets/virtual-machine-scale-sets-automatic-upgrade and seeing if we could change our VMSS (currently using a Manual upgradePolicy mode) to an automatic rolling update one but found that the application health probe couldn't use our existing App Gateway health probe as it needed to be specifically a LoadBalancer one. Bummer.

Anyhow, I thought I'd test our VMSS to ensure we can manually Upgrade each instance from the Portal/CLI but deliberately picking an old 16.04 LTS image id (instead of the 'latest' version tag). From "az vm image list --location canadacentral --publisher Canonical --offer UbuntuServer --sku 16.04-LTS --all --output table" I picked the first 16.04 image published in 2018 ie 16.04.201801050. Latest one is "16.04.201811140"

Microsoft.Compute/virtualMachineScaleSets/cluster?api-version=2018-06-01:
```
"properties": {
    "singlePlacementGroup": false,
    "upgradePolicy": {
      "mode": "Manual",
      "automaticOSUpgrade": false
    },
    ...
    "imageReference": {
      "publisher": "Canonical",
      "offer": "UbuntuServer",
      "sku": "16.04-LTS",
      "version": "16.04.201801050"
    },
```

I can confirm that each new VMSS instance indeed has the desired "16.04.201801050" image by SSH onto the box (with plenty of updates to apply):

```
Welcome to Ubuntu 16.04.3 LTS (GNU/Linux 4.11.0-1016-azure x86_64)

 * Documentation:  https://help.ubuntu.com
 * Management:     https://landscape.canonical.com
 * Support:        https://ubuntu.com/advantage

  Get cloud support with Ubuntu Advantage Cloud Guest:
    http://www.ubuntu.com/business/services/cloud

202 packages can be updated.
118 updates are security updates.


jiraadmin@jiranode-000001:~$ apt list linux-image-azure 
Listing... Done
linux-image-azure/xenial-updates,xenial-security 4.15.0.1032.37 amd64 [upgradable from: 4.11.0.1016.16]
N: There is 1 additional version. Please use the '-a' switch to see it
```

but I was surprised to see that the Portal and REST API have each of the instances with the latest model applied set to true (which clearly it is not)

Microsoft.Compute/virtualMachineScaleSets/cluster/virtualMachines/0?api-version=2018-06-01:
```
"properties": {
    "latestModelApplied": true,
    "vmId": "...",
    "hardwareProfile": {},
    "storageProfile": {
      "imageReference": {
        "publisher": "Canonical",
        "offer": "UbuntuServer",
        "sku": "16.04-LTS",
        "version": "16.04.201801050"
      }
```      

Clicking on the Upgrade button for the VM instance in the Azure Portal kicks off a very short-lived task with no changes made to the underlying VM.

So I assumed the following:
* Specifying an older image version before the 'latest' one should have VMSS instance's latestModelApplied set to false
* Upgrading from Portal should bring the "old" image version upto the 'latest' image version ie essentially performing a 'sudo apt-get upgrade' or 'sudo apt dist-upgrade'. With latestModelApplied to false, it doesn't do either.
* Clicking on Reimage from the Portal, you get a warning about instance back to it's original state but from https://docs.microsoft.com/en-us/rest/api/compute/virtualmachinescalesets/reimage it suggests it's going to upgrade OS image ie 'sudo apt dist-upgrade'. It does the former ie reinstalls the original image blowing away everything.

So at the min it appears to me you can't use the Portal to maintain OS and security updates on the currently running VM. Is the behaviour and my assumptions above correct?

Thanks,
Stephen.

**Comment by gbowerman** [comment]
Thanks for the detailed question. Note that it is "latest model", not "latest version". What that means is the latest VMSS configuration (which you set to "16.04.201801050") has been applied to all the VMs. "Upgrading" from the portal means apply the latest VMSS model to the VM. If you set the model to an older OS version, it's still the latest model. 

Yes, Reimage sets the VM to the image referenced by the VMSS model, which in your case is a "16.04.201801050" platform image.

If you set upgradePolicy mode to "Automatic", and set the OS version to "latest" in the VMSS model, then your VMs would upgrade to the latest OS any time both of the following is true:
- a new platform image version is available
- You call reimage.
You'd also get the latest version when latest is set and you scale out (increase VMSS capacity).

Regards
Guy

**Comment by stephenmontgomery** [comment]
Hi Guy,
Thanks for the prompt response. I think I follow most of that - our VMSS "model" is just the Azure 16.04 platform image with a custom script so had assumed it would have become stale when new 16.04 Azure image becomes available.

The goal of what I'm trying to do is to ensure Admins using the Azure Portal see that security updates are available and can apply them. While I like the idea of setting the upgradePolicy to Automatic, I'd have to deploy a new load balancer just to do the health probe (we have an App Gateway with a health probe but the VMSS probe expects a standard LB one) to ensure the new updates don't break anything. Also given to v. slow cluster syncing time, we like to overprovision our VM instance count and disable autoscaling so we wouldn't get much benefit of scaling in/out.

So it sounds like to roll out 'manual' periodic security updates, we'd just have our model use latest version tag (which we did have) and click "Reimage" for each running VM instance. Hopefully when we action the reimage there is an updated OS image available and updates applied. Sound about right?

**Comment by stephenmontgomery** [comment]
Hi Guy,
Thanks again - I do like the idea of the function/lambda check + email - I think this is the best of both worlds. We're attempting to create a generic solution for both customer trialling the software (basic HW) but also providing a robust solution for large companies as well. Monitoring/upgrading nodes with OS updates is a personal thing I think - you either have dedicated maintenance windows (micro-manage it) or happy to be gong-ho! I'll let the customer decide and action.

**Comment by jlongo62** [comment]
I have a Windows 2016 ScaleSet with one instance. I have enabled  "Health and repair". The Scaleset was created with a **Gallery** Image. My gallery image definition is *vmsstest1-imagedef*. On each image the disks have specific files so I can tell if the VMSS changed. Upgrade Policy = Manual. The Scaleset **storageProfile.imageReference.id** is set as:

    /subscriptions/.../resourceGroups/rg01/providers/Microsoft.Compute/galleries/gallery1/images/vmsstest1-imagedef/versions/latest

When I create the ScaleSet, the image is loaded and appears correct. I then add a new image to the **Gallery Image Definition**. When I click on **Upgrade**, the instance status changes to Updating, then Running. However the data on the disks does not change indicating no change has occurred to the ScaleSet instance.

When I Deallocate the Scaleset and restart it, the correct image is loaded and the Scaleset imageis now appears correct.

I think from this thread, I am misunderstanding what "Upgrade Policy" and "Upgrade" button do ?

How should I configure this to make it work ? (Please provide template fragments)

**Comment by gbowerman** [comment]
@jlongo62 have you signed up for the preview here: [http://aka.ms/vmssosupgrades ](http://aka.ms/vmssosupgrades)? This should put you in touch with the folks who can authorize your subscription and provide guidance.

**Comment by jlongo62** [comment]
My simple understanding: The **Upgrade Policy** and **Upgrade** portal button does nothing unless the Scaleset "**Model**" has changed. In my case, the Scaleset is based on the "latest" image in a **Shared Image Gallery**. My Model looks like this:
 ```
"imageReference": {
    "id": "/subscriptions/.../resourceGroups/RGGallery/providers/Microsoft.Compute/galleries/MyGallery/images/imagedef1/versions/latest')]"
```
_**versions/latest** seems to be the key to using the latest image._

When I update the Gallery Image, I must **Deallocate** the **Scaleset** for the latest image to be used. _Upgrade Policy and Upgrade do nothing._ (because the Model has not changed.

I seems to me what is missing from the **Model** is something akin to the **forceUpdateTag** that is part of the Azure Extension template. _This is just a string that can be set to something different (ie random GUID)_ By providing a way to **Invalidate** the model, then  **Upgrade Policy** and **Upgrade** would work.

**Comment by SnowmanCharles** [comment]
I'm recently playing with Azure VMSS and I have a case here:
1. I pass a customdata in osProfile when creating the VMSS.
2. I then updated the customdata in osProfile. But seems old VMs will not receive that.
3. I do reimage on the old VMs. Seems like the customdata was not renewed on old VMs.

My questions are:
1.  Is osProfile.customData considered as part of VMSS model?
2. What's the right way to update the customData on my old VMs? Probably need something else besides a single reimage?
