### ISSUE TITLE
Unable to attach data disk on Low priority VMSS VMs

### ISSUE THREAD

**Issue by CoRfr** [Azure/vm-scale-sets#63]
I just spent almost a week on the phone with Azure helpdesk, and while attaching disks to VMSS Low priority used to be supported (I used it without any issues between October 2018 - March 16th 2019), it appears not to work at the moment.
We were able to reproduce the issue on the support engineer's side.

API works fine on Regular priority VMSS (PUT call on Microsoft.Compute/virtualMachineScaleSets/<VMSS>/virtualMachines/<instanceId>), but it fails on Low priority with:
```
{"error":{"code":"OperationNotAllowed","message":""}}
```
there is also a `Conflict (HTTP Status Code: 409)` thrown in the reply.

Note that it fails even if no change has been made to the JSON structure.

It is easily to reproduce by:
- creating a Low priority VMSS
- access one of the VMSS VM instance in http://resources.azure.com
- Click on 'Read-write' and 'Edit'
- No need to make any changes
- Click `PUT`
- The update fails.

Same steps works using a Regular priority VMSS.

**Comment by prafulbusa** [comment]
Thank you Bertrand for bringing this to an attention.

**Comment by gbowerman** [comment]
@CoRfr what's the support case #? I can check to make sure it's assigned to the right product team.

**Comment by CoRfr** [comment]
@gbowerman , support request id is #119031924000479

Thanks for your help.

**Comment by gbowerman** [comment]
@CoRfr the support case appears to be closed as resolved yesterday. If the issue is still present can you reopen it and ask them to escalate an ICM to the product group.

**Comment by prafulbusa** [comment]
Just spoke with Bertrand, and informed about the case update (operation to carry out the fix on this issue) etc

**Comment by CoRfr** [comment]
Is there any chance the fix could be rolled out in West US 2 as well?
This is our main region, and I could provide some feedback as I remove the mitigation on our side.

**Comment by gbowerman** [comment]
It will be soon. The support case owner should be able to work with the PMs to keep you informed of the roll-out status.

**Comment by gbowerman** [comment]
@CoRfr Azure engineering has advised this should be fixed in all regions.

**Comment by CoRfr** [comment]
@gbowerman , can confirm that it's back to normal for us, thanks for your support!
