### ISSUE TITLE
Suggestion: support for data disks created from an image

### ISSUE THREAD

**Issue by blumu** [Azure/vm-scale-sets#7]
## Feature request
Ability to provision a VM scale set where all the created VMs in the set have an attached managed data disk created from a specified image.

## Description
Right now it's only possible to create and attach empty data disks for each VM in the scale set. As documented in [Convert a scale set template to a managed disk scale set template](https://docs.microsoft.com/en-us/azure/virtual-machine-scale-sets/virtual-machine-scale-sets-convert-template-to-md#data-disks), this can be done by specifying an empty data disk in the ARM template with option `"createOption" = "empty"`. 

The proposed feature would allow setting `"createOption" = "fromImage"` in the ARM template, and allow specifying the resource id to a managed image to clone and attach to each VM in the scale set.

**Comment by gbowerman** [comment]
Thanks for this feature request. Happy to report it is possible. See: h[ttps://docs.microsoft.com/en-us/azure/virtual-machine-scale-sets/virtual-machine-scale-sets-attached-disks#adding-pre-populated-data-disks-to-an-existent-scale-set ](https://docs.microsoft.com/en-us/azure/virtual-machine-scale-sets/virtual-machine-scale-sets-attached-disks#adding-pre-populated-data-disks-to-an-existent-scale-set)

**Comment by blumu** [comment]
Thanks, I'm aware of this new solution. Unfortunately this requires to have the data disk already included in the managed image together with the OS disk. This means you first need to create a VM from your OS disk, attach the data disk, capture the VM as a managed image and then create the VM scaleset! This is not very efficient. It would work for us if there were a way to directly create an Azure managed image from an OS disk and data disk without having to first provision a VM. @gbowerman

**Comment by blumu** [comment]
@gbowerman  I found a workaround for the image creation issue. The following script can be used to attach an existing managed data disk to an existing managed image and save the result in a new image:. The resulting managed image can then be used to deploy the VM ScaleSet:
```powershell

## Create a VM image using the OS VHD from an existing VM image and 
## attaching an existing managed data disk
$rg = 'myresourcegroup'
$sourceImage = 'myManagedDiskImage'
$diskToAttach = 'managedDiskToAttach'
$targetImage = 'newVhd'

$image = Get-AzureRmImage -ResourceGroupName $rg -ImageName $sourceImage
$dataDisk = Get-AzureRmDisk -ResourceGroupName $rg -DiskName $diskToAttach
$imageConfig = New-AzureRmImageConfig -Location $image.Location
$imageConfig = Set-AzureRmImageOsDisk -Image $imageConfig -OsState 'Generalized' -OsType Windows -BlobUri $image.StorageProfile.OsDisk.BlobUri
$imageConfig = Add-AzureRmImageDataDisk -Image $imageConfig -Lun 1 -ManagedDiskId $dataDisk.Id
$newImage = New-AzureRmImage -ImageName $targetImage -ResourceGroupName $rg -Image $imageConfig
```
