### ISSUE TITLE
L4 LB across multiple scale sets

### ISSUE THREAD

**Issue by gatneil** [Azure/vm-scale-sets#9]

**Comment by gbowerman** [comment]
Thanks for opening this issue. Happy to report L4 LB across multiple scale sets is now possible with LB Standard SKU, in public preview. h[ttps://azure.microsoft.com/en-us/updates/public-preview-load-balancer-standard/](https://azure.microsoft.com/en-us/updates/public-preview-load-balancer-standard/)
